DB_PORT: 3307
DB_HOST: localhost

CURRENT_IP: 127.0.0.1

DINGTALK_SECRET: PkiCrZs1ocp2dp3vu9eqh35zhUt8wxcdH4GlfNAjday0PyzLltq5YFgoFnGVi2BH
DINGTALK_TOKEN_ID: 25237a4fbf8d819aff4d5081781338e77ca594bb94d611de1253d242c04b02b4

FILE_DIR: /var/www/data
PORT_FOR_WARDING_MIN: 8200
PORT_FOR_WARDING_MAX: 8500
GUACAMOLE_HOST: some-guacd
GUACAMOLE_PORT: 4822
GUACAMOLE_MAPPING: /tmp
